# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 791fbe4dc3cc1470348e4c4036c54bf0caba6dac7bc920ce09e91d7bdfca1329c30898f000a954d7a80ab86cbc78bb031413dd940d48c51e87dbe72f6ce167f6

test:
  secret_key_base: f489ff36495da84abf06861e3cb62f078487c2403359e72bb2faae83cae330eb25735de90ef4c5e3546d44cb710fd4355b5dc9e8d6839c49fde3ea05a2300062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
